### ISSUE TITLE
Необходимы логотипы Главпункта

### ISSUE THREAD

**Issue by SergeChepikov** [glavpunkt/Webasyst-Shopscript#10]
В формате 200x110 (это будет обложка плагина в маркетплейс, примерно https://www.webasyst.ru/store/plugin/shipping/ppoint/ как тут сверху слева)
В формате 16x16

**Comment by SergeChepikov** [comment]
И ещё 250х100

**Comment by kseniia-karasenko** [comment]
![250x100](https://user-images.githubusercontent.com/25634342/46065380-9385f200-c17a-11e8-9bd1-f318a52fdadd.png)
![16x16](https://user-images.githubusercontent.com/25634342/46065381-9385f200-c17a-11e8-985c-4615341a92f7.png)
![200x110](https://user-images.githubusercontent.com/25634342/46065382-941e8880-c17a-11e8-8ed8-b7086927cd3e.png)
